tap "homebrew/cask"
tap "github/gh"
cask_args appdir: "/Applications"

brew "ack"
brew "act"
brew "asdf"
brew "awscli@1"
brew "autojump"
brew "bat"
brew "brew-cask-completion"
brew "devtoys"
brew "dnsmasq"
brew "eslint"
brew "exercism"
brew "fzf"
brew "git"
brew "git-delta"
brew "gh"
brew "graphviz"
brew "grip"
brew "httpie"
brew "iconsur"
brew "jq"
brew "mas"
brew "navi"
brew "ncdu"
brew "openssl"
brew "prettier"
brew "watch"
brew "yarn"
brew "zplug"
brew "zsh"
brew "zsh-completions"

cask "docker"
cask "cask-fonts/font-fira-code"
cask "github"
cask "visual-studio-code"

mas "CopyClip", id: 595191960
mas "Divvy", id: 413857545
mas "Xcode", id: 497799835
