query TeamIssues($teamId: String!, $assignee: String!) {
  team(id: $teamId) {
    issues(
      filter: { assignee: { name: { eq: $assignee } } }
      first: 10
      orderBy: updatedAt
    ) {
      nodes {
        identifier
        title
        state {
          name
        }
        assignee {
          name
        }
      }
    }
  }
}
