-- Sync holds between personal (Me) and work (athal@mozilla.com) calendars
-- Mirrors the iOS Sync Calendars Shortcut as a Mac-native LaunchAgent script
--
-- Logic:
--   For each real event in calendar A → create a free hold in calendar B if none exists
--   For each hold in calendar B → remove if source event no longer exists or was cancelled
--   Holds are identified by the Marker string in Notes field
--   Holds are always "free" (not busy) — for self-organization only
--
-- Calendars
set personalCal to "Me"
set workCal to "athal@mozilla.com"
set marker to "Automatically generated by Shortcuts"
set weeksAhead to 4
set displayNames to {{"Lunch", "Lunch"}, {"Dr.", "Dr"}, {"Standup", "Standup"}, {"Retrospective", "Retrospective"}, {"Cycle Plan", "Planning"}, {"Andrew /", "1-1"}, {"Demo", "Demo"}}

-- Meetings that should NOT get a transition block (handled in transition-blocks.applescript)
-- This script only handles the hold mirror, not transition zones

on getDisplayName(eventTitle, displayNames)
  repeat with pair in displayNames
    if eventTitle contains (item 1 of pair) then
      return item 2 of pair
    end if
  end repeat
  return "Busy"
end getDisplayName

on syncDirection(sourceCal, targetCal, marker, weeksAhead, displayNames)
  tell application "Calendar"
    set now to current date
    set futureDate to now + (weeksAhead * weeks)

    -- Get all real events from source (not holds we created)
    set sourceEvents to (every event of calendar sourceCal whose ¬
      start date >= now and ¬
      start date <= futureDate and ¬
      (notes is missing value or notes does not contain marker) and ¬
      status is not cancelled)

    repeat with sourceEvt in sourceEvents
      set evtStart to start date of sourceEvt
      set evtEnd to end date of sourceEvt
      set evtTitle to summary of sourceEvt

      -- Skip declined/tentative
      try
        if status of sourceEvt is cancelled then
          -- skip
        else
          -- Check if hold already exists in target
          set existingHolds to (every event of calendar targetCal whose ¬
            start date is evtStart and ¬
            end date is evtEnd and ¬
            notes contains marker)

          if (count of existingHolds) is 0 then
            -- Create hold
            set holdTitle to my getDisplayName(evtTitle, displayNames)
            set newHold to make new event at end of events of calendar targetCal
            set summary of newHold to holdTitle
            set start date of newHold to evtStart
            set end date of newHold to evtEnd
            set notes of newHold to marker
            -- Free status so it doesn't block others
            set availability of newHold to free
          end if
        end if
      end try
    end repeat

    -- Remove stale holds: holds in target with no matching source event
    set targetHolds to (every event of calendar targetCal whose ¬
      start date >= now and ¬
      start date <= futureDate and ¬
      notes contains marker)

    repeat with hold in targetHolds
      set holdStart to start date of hold
      set holdEnd to end date of hold

      -- Look for matching source event
      set matchingSource to (every event of calendar sourceCal whose ¬
        start date is holdStart and ¬
        end date is holdEnd and ¬
        (notes is missing value or notes does not contain marker) and ¬
        status is not cancelled)

      if (count of matchingSource) is 0 then
        delete hold
      end if
    end repeat
  end tell
end syncDirection

-- Run both directions
my syncDirection(personalCal, workCal, marker, weeksAhead, displayNames)
my syncDirection(workCal, personalCal, marker, weeksAhead, displayNames)
