tap "github/gh"
tap "homebrew/cask-fonts"

brew "bat"
brew "chezmoi"
brew "git-delta"
brew "gh"
brew "jc"
brew "jq"
brew "zplug"

cask "font-monaspace"

{{ if .macos -}}
brew "autojump"
brew "mas"
brew "openssl"
brew "watch"

cask_args appdir: "/Applications"
cask "visual-studio-code"

mas "CopyClip", id: 1020812363
{{ end -}}
