tap "github/gh"

brew "ack"
brew "act"
brew "bat"
brew "chezmoi"
brew "git-delta"
brew "gh"
brew "jq"
brew "zplug"

{{ if not .codespaces -}}
brew "asdf"
brew "autojump"
brew "awscli"
brew "colima"
brew "dnsmasq"
brew "docker"
brew "iconsur"
brew "mas"
brew "openssl"
brew "watch"

tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: "/Applications"

cask "devtoys"
cask "font-fira-code"
cask "visual-studio-code"

mas "CopyClip 2", id: 1020812363
mas "Divvy", id: 413857545
{{ end -}}
